services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.20.1
    container_name: mealie
    restart: always

    deploy:
      resources:
        limits:
          memory: 1000M # limit memory
    volumes:
      - mealie-data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      API_PORT: 9925
      DB_ENGINE: sqlite
      TZ: UTC
      BASE_URL: https://${MEALIE_DOMAIN}
      # Email config
      SMTP_HOST: ${MEALIE_EMAIL_HOST}
      SMTP_PORT: ${MEALIE_EMAIL_PORT}
      SMTP_AUTH_STRATEGY: ${MEALIE_EMAIL_AUTH}
      SMTP_FROM_EMAIL: ${MEALIE_EMAIL}
      SMTP_USER: ${MEALIE_EMAIL}
      SMTP_PASSWORD: ${MEALIE_EMAIL_PW}
    networks:
        - rev-proxy-net

volumes:
  mealie-data:

networks:
  rev-proxy-net:
    external: true
    name: rev-proxy-net
